require("dotenv").config();const express=require("express"),cors=require("cors"),mysql=require("mysql2/promise"),bcrypt=require("bcryptjs");const app=express();app.use(cors());app.use(express.json());const pool=mysql.createPool({host:process.env.DB_HOST||"localhost",user:process.env.DB_USER||"root",password:process.env.DB_PASSWORD||"",database:process.env.DB_NAME||"matcha_house",connectionLimit:10});
async function seed(){const [r]=await pool.query("SELECT id FROM users WHERE username='admin'");if(!r.length){const hash=await bcrypt.hash("admin123",10);await pool.query("INSERT INTO users(name,username,password,role) VALUES(?,?,?,?)",["Administrator","admin",hash,"admin"]);}}
app.get("/",(_,res)=>res.send("Matcha House API berjalan!"));app.get("/test-db",async(_,res)=>{try{await pool.query("SELECT 1");res.send("Database matcha_house berhasil terhubung!")}catch(e){res.status(500).send(e.message)}});
app.get("/api/products",async(_,res)=>{try{const[r]=await pool.query("SELECT * FROM products ORDER BY id DESC");res.json(r)}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/products",async(req,res)=>{try{const{x}=req.body;const{name,category,price,stock,description,emoji}=req.body;if(!name)return res.status(400).json({message:"Nama wajib diisi"});const[r]=await pool.query("INSERT INTO products(name,category,price,stock,description,emoji) VALUES(?,?,?,?,?,?)",[name,category||"Classic",price,stock,description||"",emoji||"🍵"]);res.json({id:r.insertId})}catch(e){res.status(500).json({message:e.message})}});
app.delete("/api/products/:id",async(req,res)=>{try{await pool.query("DELETE FROM products WHERE id=?",[req.params.id]);res.json({message:"Menu dihapus"})}catch(e){res.status(500).json({message:e.message})}});app.patch("/api/products/:id/stock",async(req,res)=>{try{await pool.query("UPDATE products SET stock=GREATEST(0,stock+?) WHERE id=?",[Number(req.body.delta||0),req.params.id]);res.json({message:"OK"})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{const[r]=await pool.query("SELECT * FROM users WHERE username=?",[req.body.username]);if(!r.length||!(await bcrypt.compare(req.body.password,r[0].password)))return res.status(401).json({message:"Username atau password salah"});const u={...r[0]};delete u.password;res.json({user:u})}catch(e){res.status(500).json({message:e.message})}});app.get("/api/users",async(_,res)=>{const[r]=await pool.query("SELECT id,name,username,role,created_at FROM users ORDER BY id DESC");res.json(r)});
app.get("/api/dashboard",async(_,res)=>{try{const[[a]]=await pool.query("SELECT COUNT(*) products,COALESCE(SUM(stock),0) stock FROM products"),[[b]]=await pool.query("SELECT COUNT(*) transactions,COALESCE(SUM(total),0) revenue FROM transactions");res.json({...a,...b})}catch(e){res.status(500).json({message:e.message})}});app.get("/api/transactions",async(_,res)=>{const[r]=await pool.query("SELECT t.*,u.name user_name FROM transactions t LEFT JOIN users u ON t.user_id=u.id ORDER BY t.id DESC");res.json(r)});app.get("/api/reports/summary",async(_,res)=>{const[[a]]=await pool.query("SELECT COUNT(*) total,COALESCE(SUM(total),0) revenue FROM transactions"),[[b]]=await pool.query("SELECT COALESCE(SUM(qty),0) items_sold FROM transaction_items");res.json({...a,...b})});
async function order(body){const c=await pool.getConnection();try{await c.beginTransaction();let total=0,ds=[];for(const i of body.items){const[r]=await c.query("SELECT id,name,price,stock FROM products WHERE id=? FOR UPDATE",[i.product_id]);if(!r.length)throw Error("Produk tidak ditemukan");const p=r[0],q=Number(i.qty);if(q<1||p.stock<q)throw Error(`Stok ${p.name} tidak cukup`);const sub=Number(p.price)*q;total+=sub;ds.push({p,q,sub})}if(Number(body.paid)<total)throw Error("Pembayaran kurang");const change=Number(body.paid)-total;const[r]=await c.query("INSERT INTO transactions(user_id,customer_name,phone,total,paid,change_amount) VALUES(?,?,?,?,?,?)",[body.userId||null,body.customer_name||"Customer",body.phone||"",total,body.paid,change]);for(const d of ds){await c.query("INSERT INTO transaction_items(transaction_id,product_id,product_name,price,qty,subtotal) VALUES(?,?,?,?,?,?)",[r.insertId,d.p.id,d.p.name,d.p.price,d.q,d.sub]);await c.query("UPDATE products SET stock=stock-? WHERE id=?",[d.q,d.p.id])}await c.commit();return{transaction_id:r.insertId,total,change}}catch(e){await c.rollback();throw e}finally{c.release()}}app.post("/api/public/orders",async(req,res)=>{try{res.json(await order(req.body))}catch(e){res.status(400).json({message:e.message})}});app.post("/api/transactions",async(req,res)=>{try{res.json(await order(req.body))}catch(e){res.status(400).json({message:e.message})}});
const port=process.env.PORT||5000;app.listen(port,async()=>{try{await seed();console.log(`Matcha House API http://localhost:${port}`)}catch(e){console.error(e.message)}});